version: '3.8'
services:
  redis:
    image: redis:6-alpine
    container_name: etl_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
celery_beat:
    build: .
    container_name: etl_celery_beat
    command: celery -A app.celery_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app/app
      - ./data:/app/data # Mount data volume for sqlite
      - ./requirements.txt:/requirements.txt
    depends_on:
      - redis
    env_file:
      - .env # If you have sensitive env variables, use this. For now, config.py handles it.
celery_worker_gmail:
    build: .
    container_name: etl_celery_worker_gmail
    command: celery -A app.celery_app worker -l info -Q gmail_queue -n gmail_worker@%h
    volumes:
      - ./app:/app/app
      - ./data:/app/data # Mount data volume for sqlite
      - ./requirements.txt:/requirements.txt
    depends_on:
      - redis
    env_file:
      - .env
celery_worker_parser:
    build: .
    container_name: etl_celery_worker_parser
    command: celery -A app.celery_app worker -l info -Q parser_queue -n parser_worker@%h
    volumes:
      - ./app:/app/app
      - ./data:/app/data # Mount data volume for sqlite
      - ./requirements.txt:/requirements.txt
    depends_on:
      - redis
    env_file:
      - .env
celery_worker_db_saver:
    build: .
    container_name: etl_celery_worker_db_saver
    command: celery -A app.celery_app worker -l info -Q db_saver_queue -n db_saver_worker@%h
    volumes:
      - ./app:/app/app
      - ./data:/app/data # Mount data volume for sqlite
      - ./requirements.txt:/requirements.txt
    depends_on:
      - redis
    env_file:
      - .env
volumes:
  redis_data:
  # data: # No need to declare if it's a bind mount
